#!/bin/bash
# Techni world script

printf "\n"
printf "\n\e[0;36m :::::::::::::                  "
printf "\n\e[0;36m      ::         ::         ::  "
printf "\n\e[0;36m       ::       ::::       ::   "  
printf "\n\e[0;36m        ::     ::  ::     ::    "
printf "\n\e[0;36m         ::   ::    ::   ::     "
printf "\n\e[0;36m          :: ::      :: ::      "
printf "\n\e[0;36m           ::         ::        "  
printf "\n"
printf        "\e[0;32m      -Techni-World script- V1.0 "
printf "\n"
echo -e " welcome to our group by\e[32m coders and hackers style"
printf "\n"
printf "\e[31m visit our website \e[34m techni-world.com and our youtube channel "
printf "\n\n\n"
printf "                                   __   Dino say : www.techni-world.com \n"
printf "                                  / _)             and hack the planet"
echo "${STR}"
printf "                           .-^^^-/ /  \n"
printf "                        __/       /  \n"
printf "                       <__.|_|-|_|  \n"
printf "\n\n\t\t\t"
echo "${PUNCH}"
printf "\n\n"